package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

func main() {
	root := "."
	if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if !info.IsDir() {
			return nil
		}
		name := filepath.Base(path)
		if name != "." && strings.HasPrefix(name, ".") {
			return filepath.SkipDir
		}
		if name == "vendor" || name == "testdata" {
			return filepath.SkipDir
		}
		processPackage(path)
		return nil
	}); err != nil {
		log.Fatal(err)
	}
}

type structToReset struct {
	name   string
	fields *ast.FieldList
}

func processPackage(dir string) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go") && fi.Name() != "reset.gen.go"
	}, parser.ParseComments)
	if err != nil {
		return
	}

	for _, pkg := range pkgs {
		typeMap := collectTypes(pkg)
		var found []structToReset

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				gd, ok := decl.(*ast.GenDecl)
				if !ok || gd.Tok != token.TYPE {
					continue
				}
				for _, spec := range gd.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}
					if hasGenerateReset(gd.Doc) || hasGenerateReset(ts.Doc) {
						found = append(found, structToReset{
							name:   ts.Name.Name,
							fields: st.Fields,
						})
					}
				}
			}
		}

		if len(found) > 0 {
			generateFile(dir, pkg.Name, found, typeMap)
		}
	}
}

func collectTypes(pkg *ast.Package) map[string]ast.Expr {
	types := make(map[string]ast.Expr)
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if ok {
					types[ts.Name.Name] = ts.Type
				}
			}
		}
	}
	return types
}

func hasGenerateReset(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func generateFile(dir, pkgName string, structs []structToReset, typeMap map[string]ast.Expr) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by reset generator; DO NOT EDIT.\n\npackage %s\n", pkgName)

	for _, s := range structs {
		rcv := receiverName(s.name)
		fmt.Fprintf(&buf, "\nfunc (%s *%s) Reset() {\n", rcv, s.name)
		fmt.Fprintf(&buf, "if %s == nil {\nreturn\n}\n\n", rcv)

		if s.fields != nil {
			for _, field := range s.fields.List {
				for _, name := range getFieldNames(field) {
					if code := fieldResetCode(rcv+"."+name, field.Type, typeMap); code != "" {
						fmt.Fprintf(&buf, "%s\n", code)
					}
				}
			}
		}

		fmt.Fprintf(&buf, "}\n")
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("format error for %s: %v", dir, err)
		src = buf.Bytes()
	}

	if err := os.WriteFile(filepath.Join(dir, "reset.gen.go"), src, 0644); err != nil {
		log.Printf("write error for %s: %v", dir, err)
	}
}

func receiverName(name string) string {
	if name == "" {
		return "x"
	}
	return string(unicode.ToLower(rune(name[0])))
}

func getFieldNames(f *ast.Field) []string {
	if len(f.Names) > 0 {
		names := make([]string, len(f.Names))
		for i, n := range f.Names {
			names[i] = n.Name
		}
		return names
	}
	if name := exprTypeName(f.Type); name != "" {
		return []string{name}
	}
	return nil
}

func exprTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return exprTypeName(t.X)
	case *ast.SelectorExpr:
		return t.Sel.Name
	default:
		return ""
	}
}

var zeroValues = map[string]string{
	"int": "0", "int8": "0", "int16": "0", "int32": "0", "int64": "0",
	"uint": "0", "uint8": "0", "uint16": "0", "uint32": "0", "uint64": "0",
	"uintptr": "0", "float32": "0", "float64": "0",
	"complex64": "0", "complex128": "0",
	"byte": "0", "rune": "0",
	"string": `""`, "bool": "false",
	"error": "nil", "any": "nil",
}

func fieldResetCode(access string, typ ast.Expr, typeMap map[string]ast.Expr) string {
	switch t := typ.(type) {
	case *ast.Ident:
		if zv, ok := zeroValues[t.Name]; ok {
			return fmt.Sprintf("%s = %s", access, zv)
		}
		if underlying, ok := typeMap[t.Name]; ok {
			if _, isStruct := underlying.(*ast.StructType); isStruct {
				return resetMethodCall(access, false)
			}
			return fieldResetCode(access, underlying, typeMap)
		}
		return resetMethodCall(access, false)

	case *ast.ArrayType:
		if t.Len == nil {
			return fmt.Sprintf("%s = %s[:0]", access, access)
		}
		return ""

	case *ast.MapType:
		return fmt.Sprintf("clear(%s)", access)

	case *ast.StarExpr:
		return ptrResetCode(access, t.X, typeMap)

	case *ast.SelectorExpr:
		return resetMethodCall(access, false)

	case *ast.StructType:
		return resetMethodCall(access, false)

	case *ast.InterfaceType, *ast.FuncType, *ast.ChanType:
		return fmt.Sprintf("%s = nil", access)

	default:
		return ""
	}
}

func ptrResetCode(access string, elem ast.Expr, typeMap map[string]ast.Expr) string {
	switch t := elem.(type) {
	case *ast.Ident:
		if zv, ok := zeroValues[t.Name]; ok {
			return fmt.Sprintf("if %s != nil {\n*%s = %s\n}", access, access, zv)
		}
		if underlying, ok := typeMap[t.Name]; ok {
			if _, isStruct := underlying.(*ast.StructType); isStruct {
				return resetMethodCall(access, true)
			}
			return ptrResetCode(access, underlying, typeMap)
		}
		return resetMethodCall(access, true)

	case *ast.ArrayType:
		if t.Len == nil {
			return fmt.Sprintf("if %s != nil {\n*%s = (*%s)[:0]\n}", access, access, access)
		}
		return ""

	case *ast.MapType:
		return fmt.Sprintf("if %s != nil {\nclear(*%s)\n}", access, access)

	case *ast.StarExpr:
		return fmt.Sprintf("if %s != nil {\n*%s = nil\n}", access, access)

	case *ast.SelectorExpr:
		return resetMethodCall(access, true)

	case *ast.StructType:
		return resetMethodCall(access, true)

	case *ast.InterfaceType, *ast.FuncType, *ast.ChanType:
		return fmt.Sprintf("if %s != nil {\n*%s = nil\n}", access, access)

	default:
		return ""
	}
}

func resetMethodCall(access string, isPointer bool) string {
	if isPointer {
		return fmt.Sprintf("if %s != nil {\nif resetter, ok := any(%s).(interface{ Reset() }); ok {\nresetter.Reset()\n}\n}", access, access)
	}
	return fmt.Sprintf("if resetter, ok := any(&%s).(interface{ Reset() }); ok {\nresetter.Reset()\n}", access)
}
